### PR TITLE
RC 12

### LINKED ISSUE #12: Add Flow / performance monitors
Often in big projects shared amongst many people, it can become hard to keep track of code. One might be confused as to what methods do, what sort of parameters they take, and what type they return. Javascript's weakly typed variables make this even more challenging. In an attempt to solve this problem, the branch associated with this issue will be focused on adding [Flow](https://flow.org/) annotations and documentation to functions, as well as including some sort of React performance checker.

### PR DESCRIPTION
**Pull request by amgoodfellow**
Closes #12
After this, it is up to contributors to make sure their stuff is well documented. Perhaps some guidelines will be put in a contributors file if more people start contributing to the project

### CODE REVIEW

**Review by kdjohnson — COMMENTED** [review]
Changing the expected type for getWeeksOfMonth from `Date` to  `number` does not fail on anything.

**Comment by amgoodfellow** [comment]
Lol. The whole purpose of having it doesn't work :laughing: 
I'll be looking into this, but it's a back-burner sort of issue. We're being pushed for a release right now 
¯\_(ツ)_/¯

**Comment by kdjohnson** [comment]
You dropped this \\

**Comment by kdjohnson** [comment]
Leaving open until we have time to look more deeply into this.

**Comment by kdjohnson** [comment]
Closing.

**Pull request closed without merging**
