### PR TITLE
RC 15

### LINKED ISSUE #15: Fix Titlebar Bug
There is a problem paginating currently with the titlebar. Sometimes strange behavior occurs on weekview and scheduleview.

### PR DESCRIPTION
**Pull request by amgoodfellow**
Closes #15

### CODE REVIEW

**Review by kdjohnson — COMMENTED** [review]
The titlebar seems to be displaying the correct date range. However, for screen reading purposes it looks like it is only incrementing by one day instead of seven for weekview. The start/end of term snackbar close button is doing some weird stuff. It comes into view then just slowly runs away.

**Review by kdjohnson — CHANGES_REQUESTED** [review]
So we should probably fix these issues before merging to master.

**Comment by kdjohnson** [comment]
It looks like ChromeVox is actually manipulating the page and is interfering with snackbar.

**Comment by amgoodfellow** [comment]
Aria label problems have been fixed - it was a simple array indexing issue. The chromevox bug I'm not sure what's going on. Also, I'd like to continue not being screenreader specific. We'll follow ADA standards and remain SR agnostic

**Review by kdjohnson — APPROVED** [review]
Works correctly now.

**Pull request merged**
