### PR TITLE
Addresses #49

### LINKED ISSUE #49: Calendar doesn't change terms when termBounds are changed

### PR DESCRIPTION
**Pull request by amgoodfellow**
Closes #49

### CODE REVIEW

**Review by kdjohnson — CHANGES_REQUESTED** [review]
Remove logging please

**Comment by kdjohnson** [comment]
Also I get this error ` Unknown prop "contentProps" on <div> tag. Remove this prop from the element.` in `MonthView` when I paginate to the beginning of the term.

**Comment by kdjohnson** [comment]
I get this ` addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded` when I change to the schedule view

**Comment by amgoodfellow** [comment]
Nice catch on the logging, and I fixed the contentProp warning. That third one I'm not able to duplicate. When exactly do you get it?

**Comment by kdjohnson** [comment]
As soon as I change to the schedule view

**Comment by amgoodfellow** [comment]
To update, for posterity, KaJuan was testing the calendar in his courses portlet and found this issue. The error is being caused by a ref attribute on a Paper component. Also, because of this, I realized the calendar is needlessly causing courses to pull in React as a dependency twice. The next push will delete the ref and add `react` and `react-dom` as peer dependencies.

**Review by kdjohnson — APPROVED** [review]

**Pull request merged**
